Debounce, LlamaCpp support, expose prompt as setup option, fix passing parameters to model (ollama)
tzachar/cmp-ai pull request #11
Opened 2023-12-19 15:05 UTC by JoseConseco

Hi,
This pr fixes https://github.com/tzachar/cmp-ai/issues/8

And gives u ability to customize prompt, and adds debounce delay:
![image](https://github.com/tzachar/cmp-ai/assets/13521338/3ed4221b-3f49-43cc-bcc1-970748242fe4)

debounce_delay -  request will be send after x ms, after last key press. 
And added support for [Llama Server](https://github.com/ggerganov/llama.cpp/blob/master/examples/server/README.md)

2023-12-20 15:13 UTC, tzachar requested changes
Overall, I think this should be split into 2 PRs.
First one, which looks pretty good, should be the ollama part.
Second one should concentrate on the debounce implementation.

2023-12-20 15:13 UTC, tzachar commented on lua/cmp_ai/source.lua
> +    -- callback() -- ? forwhat
this is part of cmp api. It is needed, please do not comment it out.

2023-12-20 15:13 UTC, tzachar commented on lua/cmp_ai/source.lua
> +function Source:trigger(ctx, callback)
I am not comfortable with this entire debounce concept.
First, I dont think it is need here. cmp already has a debounce implementation.
Second, I think this implementation is wrong; there should not be a global autocommand which handles the debounce.

2023-12-25 05:26 UTC, ALameLlama commented
+1 for fixing the ollama params, without this, you can't change it to a remote host.

2023-12-26 23:00 UTC, mark64 commented on lua/cmp_ai/backends/ollama.lua
> +  self.params = vim.tbl_deep_extend('keep', o or {}, {
Does this bug apply to the `openai` or `bard` backends as well? They similarly use `params` instead of `o`

2024-01-10 09:10 UTC, tzachar commented
@JoseConseco 
Any updates?

2024-01-10 13:35 UTC, JoseConseco commented
I will have to google, how do I split this into multiple pr - with one file per PR.

2024-01-11 07:08 UTC, tzachar commented
> I will have to google, how do I split this into multiple pr - with one file per PR.

The point here is that I do not believe debounce should be implemented inside this plugin, as cmp already implements debounce.
You have yet to convince me it is needed here. If you do manage to, we can merge this as is after addressing the other issues.

2024-01-11 10:41 UTC, JoseConseco commented on lua/cmp_ai/backends/ollama.lua
> +  self.params = vim.tbl_deep_extend('keep', o or {}, {
I do not know, since I do not used Bard and openai.  I can only assume that if they work ok, then this line is not needed.

2024-01-11 10:59 UTC, JoseConseco commented on lua/cmp_ai/source.lua
> +function Source:trigger(ctx, callback)
Built in debounce in cmp - has issue where it is not working  as it should:
- to my understanding, it should show completion popup  x mseconds  after last key press in insert mode
- But what it does - it shows completion x ms after typing in first letter in insert mode. 
I tested this with 2 second delay,   and cmp will not wait for last key press. 
In my implementation it will wait till last key is pressed - thus it wont spin my gpu fans as much. I'm not sure if the implementation is ok, I just copied someone else code. I know that   copilot - cmp extension is also using its own debounce code.

2024-01-11 13:08 UTC, tzachar commented on lua/cmp_ai/source.lua
> +    -- callback() -- ? forwhat
@JoseConseco 
Can you please remove the comment here?

2024-01-11 13:18 UTC, tzachar commented on lua/cmp_ai/source.lua
> +function Source:trigger(ctx, callback)
ok, looking at cmp sources I can only agree.

2024-01-11 16:40 UTC, JoseConseco commented on lua/cmp_ai/source.lua
> +    -- callback() -- ? forwhat
ok. done. Also hope u dont mind, but I commented out second  `conf:get('notify_callback')('Completion started')` since it was displaying same notification 2x .

2024-01-12 15:06 UTC, JoseConseco commented
@tzachar let me know if all is ok now.

2024-02-08 02:58 UTC, heyfixit commented on README.md
> +      return prompt = '<PRE> ' .. lines_before .. ' <SUF>' .. lines_after .. ' <MID>', -- for codellama
```suggestion
      return '<PRE> ' .. lines_before .. ' <SUF>' .. lines_after .. ' <MID>' -- for codellama
```

2024-02-08 08:37 UTC, tzachar commented
> @tzachar let me know if all is ok now.

see pending issues in the review.

2024-02-09 16:27 UTC, JoseConseco commented
> > @tzachar let me know if all is ok now.
> 
> see pending issues in the review.
Ah, ok I though it is up to you to accept the changes and mark them as resolved.  Will do it right now.

2024-02-09 16:31 UTC, JoseConseco commented on README.md
> +      return prompt = '<PRE> ' .. lines_before .. ' <SUF>' .. lines_after .. ' <MID>', -- for codellama
fixed in 4442111e6e0d8691b476ea271018a918e6cd2712

2024-03-12 21:18 UTC, mdietrich16 commented
+1 or fast merge. Maybe the debounce stuff should be done as a PR to `cmp` then?

2024-03-13 09:44 UTC, tzachar commented
> +1 for fast merge. Maybe the debounce stuff should be done as a PR to `cmp` then?

Waiting for the last issue to be resolved.

2026-02-08 09:55 UTC, closed without merging