ollama and requests: support proper streaming
tzachar/cmp-ai pull request #14
Opened 2024-03-15 19:16 UTC by maxwell-bland

Supports proper streaming of inputs via curl and incremental building of autocomplete suggestions for Ollama. This is necessary on lower-end or non-GPU machines. Additionally, kills previous curl calls to ensure that multiple curls will not be fired in a row during autocomplete, which kills the ollama server.

Needs testing on non-ollama services (I have no access).

Thanks!
Maxwell

2024-03-18 14:05 UTC, maxwell-bland commented
Update, this also has a back-end issue since Ollama's http server is stateful and does not handle canceling curl very well. Potentially the ollama backend should be reworked to use a pipe to `ollama run` directly.

https://github.com/ollama/ollama/issues/3225

2024-03-20 09:01 UTC, tzachar commented
@maxwell-bland 
waiting for you to address my comments.
10x

2024-03-21 13:25 UTC, maxwell-bland commented
@tzachar not sure they went through, the merge pull request above should highlight review changes?

I need to fix ollama's http server setup to add appropriate request cancellation so it doesn't get flooded, but do not have an abundance of time just yet, hopefully this weekend

2024-03-24 07:39 UTC, tzachar commented
@maxwell-bland 
You did not push any more changes to your branch.

2024-03-24 14:22 UTC, maxwell-bland commented
@tzachar sorry if it was not clear: your comments did not get posted, as far as I can see. What is your opinion on the change? Were there some comments in the code that I missed?

I think it is fine to use curl in the short term, but it would probably be better to switch it to a subprocess that works via pipes since it would reduce latency and difficulties in managing requests. Any reason you chose curl for this in particular instead?

I looked at adding timeout/session management to ollama yesterday but it will be a bit of a slog. I needed to get other work out of the way before fixing this.

2024-03-25 09:52 UTC, tzachar commented
@maxwell-bland you can see my comments above in this thread, with a `pending` badge.

2024-03-25 13:59 UTC, maxwell-bland reviewed
This is how you leave a comment

2024-03-28 09:49 UTC, tzachar commented
All my comments are included inside gitlab's review process.
you can access it from the top of the pull request (https://github.com/tzachar/cmp-ai/pull/14/files/f4877c51e2c4354dea5eb3ffa95530b481b7c8d3).
search for "view reviewed changes"

2024-04-10 08:10 UTC, tzachar requested changes

2024-04-10 08:10 UTC, tzachar commented
Thanks @alexandradeas 
My bad.

2026-02-08 09:55 UTC, closed without merging