feat: add support for suffix parameter in ollama
tzachar/cmp-ai pull request #25
Opened 2024-07-30 08:57 UTC by milafrerichs

## What does this PR do?
This PR adds support for the suffix parameter in Ollama. 
The ollama API does support a suffix parameter for FIM requests/models: https://github.com/ollama/ollama/blob/main/docs/api.md#parameters

Via a function call similar to the prompts we can add the suffix which typically would be `lines_after`.
usage:
```lua
provider_options = {
    suffix = function(lines_after)
        return lines_after
    end,
}
```
For example codegemma a popular FIM model has the following template:
```
{{- if .Suffix }}<|fim_prefix|>{{ .Prompt }}<|fim_suffix|>{{ .Suffix }}<|fim_middle|>
{{- else }}{{ .Prompt }}
{{- end }}
```
this allows us to use the suffix and not change the template

Support was added here: https://github.com/ollama/ollama/pull/5207

2024-07-30 11:40 UTC, tzachar requested changes
Please add proper documentations and example usage.
10x

2024-07-30 12:13 UTC, milafrerichs commented
@tzachar is that sufficient or do you want something more specific?

2024-07-30 12:26 UTC, tzachar commented on README.md
> +With Ollama you can also use the `suffix` parameter, typically when you want to use cmd-ai for codecompletion.
typo: cmd -> cmp

2024-07-30 12:27 UTC, tzachar commented on README.md
> +    suffix = function(lines_after)
Can you give an example other than the default? Otherwise, why would you need this parameter??

2024-07-30 13:46 UTC, milafrerichs commented on README.md
> +    suffix = function(lines_after)
there is no default. the default is empty/not set. 

you would need this parameter if you would want to use the FIM template from the Model and not generate the whole prompt.
you would need to go to all models and figure out their template. if you use suffix you can just use the `lines_before` and `lines_after` and ollama and the modelfile would take care of the rest. 

if you don't want the change, no worries just close the PR.

2024-07-30 15:29 UTC, tzachar commented on README.md
> +    suffix = function(lines_after)
I dont understand. Why cant you give a pecific working example? It can be tailored to your use case.

2024-07-31 10:35 UTC, milafrerichs commented on README.md
> +    suffix = function(lines_after)
@tzachar thinking further I think my proposal #26 might expain it a bit more and propose a different change.

2024-07-31 11:24 UTC, tzachar commented on README.md
> +    suffix = function(lines_after)
I am really ok with the change, Im just asking that the same writeup you have in #26 should go into the docs. Otherwise, no one but you would know how to use it.

2024-08-01 07:08 UTC, merged